export const RELEASE_ANNOUNCEMENT = Object.freeze({
  id: 'thunderlink-whats-new-0.3.29',
  range: '0.3.10 — 0.3.29',
  title: 'God’s Eye evolved',
  intro: 'A field briefing on the systems, live-data layers, reliability work, and owner controls added since build 0.3.10.',
  releases: Object.freeze([
    { version: '0.3.10', title: 'Steam request hardening', summary: 'Bounded concurrent Steam requests, transient retries, and provider-safe failure handling.' },
    { version: '0.3.11', title: 'Intelligence Console', summary: 'Authenticated intelligence workspace, role controls, public-source lookups, and provider health.' },
    { version: '0.3.12', title: 'Geospatial weather operations', summary: 'Live radar and official warning polygons moved onto the globe as independently governed layers.' },
    { version: '0.3.13', title: 'Weather startup recovery', summary: 'Corrected weather middleware startup so Railway deployments initialize cleanly.' },
    { version: '0.3.14', title: 'Intelligence access recovery', summary: 'Removed a loading-cover conflict that could hide the authenticated Intelligence Console.' },
    { version: '0.3.15', title: 'Interactive intelligence channels', summary: 'Clickable live overview channels with operational records and source drill-downs.' },
    { version: '0.3.16', title: 'Live fusion schematic', summary: 'Source-backed aggregation telemetry plus complete Washington 511 camera placement coverage.' },
    { version: '0.3.17', title: 'Expanded U.S. 511 network', summary: 'Large official camera catalogs, isolated provider health, and performance-safe loading.' },
    { version: '0.3.18', title: 'Northeast corridor expansion', summary: 'Virginia, Pennsylvania, New Jersey, New York, and Massachusetts 511 integrations.' },
    { version: '0.3.19', title: 'Southeast and New England', summary: 'Tennessee, South Carolina, Alabama, Ohio, Vermont, and Connecticut camera catalogs.' },
    { version: '0.3.20', title: 'Central states and filters', summary: 'Twelve additional state catalogs plus persistent per-state camera visibility controls.' },
    { version: '0.3.21', title: 'CCTV projection recovery', summary: 'Corrected black map projections while retaining the latest valid camera frame.' },
    { version: '0.3.22', title: 'CCTV watch routes', summary: 'Live projection, enlarged viewing, multi-camera mosaics, and bounded watch-route cycling.' },
    { version: '0.3.23', title: 'Native-resolution viewing', summary: 'Fit and 1:1 modes expose provider resolution honestly without artificial enlargement.' },
    { version: '0.3.24', title: 'Owner vehicle classification', summary: 'Owner-only, non-identifying vehicle type, color, likely model, and broad year observations.' },
    { version: '0.3.25', title: 'Six-state camera expansion', summary: 'Rhode Island, New Hampshire, Maine, West Virginia, Kentucky, and expanded Missouri coverage.' },
    { version: '0.3.26', title: 'Interactive CCTV controls', summary: 'Restored pointer access to Close, Multi View, Fit, and 1:1 controls in the large viewer.' },
    { version: '0.3.27', title: 'Protected-frame foundation', summary: 'Dormant, owner-controlled detector-only redaction and short-lived protected frame storage.' },
    { version: '0.3.28', title: 'Release briefing', summary: 'Once-per-account What’s New briefings with an owner-controlled system-wide switch.' },
    { version: '0.3.29', title: 'Provider resilience', summary: 'Correct OpenSky OAuth refresh and failure diagnostics, plus fail-soft terrain retries and circuit breaking.' },
  ]),
  comingSoon: Object.freeze([
    { title: 'Scene Director', summary: 'Cinematic scene controls remain staged while visual-state transitions are hardened.' },
    { title: 'Law Enforcement Transmissions', summary: 'Jurisdiction-aware authorized stream playback remains staged pending provider-ready integration.' },
    { title: 'Protected Archive deployment', summary: 'The privacy-redaction worker remains off until the owner configures and deliberately enables it.' },
    { title: 'Additional 511 coverage', summary: 'More official state and regional camera catalogs will be added as stable provider access is verified.' },
  ]),
});
